services:
  postgres-db:
    image: postgres:17-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-reginald}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER:-postgres}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  gateway:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: gateway
    container_name: reginald-gateway
    ports:
      - "8088:8080"
    environment:
      - AUTH_SERVICE_URL=http://reginald-auth:8081
      - USERS_SERVICE_URL=http://reginald-users:8083
      - TASKS_SERVICE_URL=http://reginald-tasks:8082
      - REQUESTS_SERVICE_URL=http://reginald-requests:8084
      - DATABASE_URL=postgres://${DB_USER:-postgres}:${DB_PASSWORD:-postgres}@postgres-db:5432/${DB_NAME:-reginald}?sslmode=disable
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      postgres-db:
        condition: service_healthy
      auth-service:
        condition: service_started
      users-service:
        condition: service_started
      tasks-service:
        condition: service_started
      requests-service:
        condition: service_started

  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: auth
    container_name: reginald-auth
    environment:
      - DATABASE_URL=postgres://${DB_USER:-postgres}:${DB_PASSWORD:-postgres}@postgres-db:5432/${DB_NAME:-reginald}?sslmode=disable
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      postgres-db:
        condition: service_healthy

  users-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: users
    container_name: reginald-users
    environment:
      - DATABASE_URL=postgres://${DB_USER:-postgres}:${DB_PASSWORD:-postgres}@postgres-db:5432/${DB_NAME:-reginald}?sslmode=disable
      - ADMIN_NAME=${ADMIN_NAME}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    depends_on:
      postgres-db:
        condition: service_healthy

  tasks-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: tasks
    container_name: reginald-tasks
    environment:
      - DATABASE_URL=postgres://${DB_USER:-postgres}:${DB_PASSWORD:-postgres}@postgres-db:5432/${DB_NAME:-reginald}?sslmode=disable
    depends_on:
      postgres-db:
        condition: service_healthy

  requests-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: requests
    container_name: reginald-requests
    environment:
      - DATABASE_URL=postgres://${DB_USER:-postgres}:${DB_PASSWORD:-postgres}@postgres-db:5432/${DB_NAME:-reginald}?sslmode=disable
    depends_on:
      postgres-db:
        condition: service_healthy
volumes:
  pgdata:
